Q_DATA_USAGE_FMT = "select report_date, total_data from usage_report where phone_number = {};"
Q_DATA_USAGE_MEAN = "select date_format(report_date, '%m-%Y') as report_date, sum(total_data)/count(total_data) as total_data from usage_report group by date_format(report_date, '%m-%Y')"
Q_MINUTES_FMT = "select report_date, total_minutes from usage_report where phone_number = {};"
Q_MESSAGES_FMT = "select report_date, total_messages from usage_report where phone_number = {};"
Q_PHONE_NUMBERS = "SELECT distinct phone_number FROM usage_report;"
Q_TOTAL_COMMUNICATION_FMT = "select report_date, avg(total_data), avg(total_minutes), avg(total_messages) from usage_report where phone_number = {};"
Q_STANDARD_DEV_COMMUNICATION = "select std(total_data), std(total_minutes), std(total_messages) from usage_report"
Q_MEAN_COMMUNICATION = "select avg(total_data), avg(total_minutes), avg(total_messages) from usage_report;"
Q_MAX_COMMUNICATION = "select max(total_data), max(total_minutes), max(total_messages) from usage_report;"
Q_MIN_COMMUNICATION = "select min(total_data), min(total_minutes), min(total_messages) from usage_report;"
